title: Cole
url: https://coleiscool.com
markdown: kramdown
kramdown:
  input: GFM
permalink: /posts/:year/:month/:day/:title/
collections:
  media:
    output: false
exclude:
  - README.md
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
